# Generated by Django 6.0 on 2026-01-04 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("education_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name": "Курс", "verbose_name_plural": "Курсы"},
        ),
        migrations.AlterModelOptions(
            name="lesson",
            options={"verbose_name": "Урок", "verbose_name_plural": "Уроки"},
        ),
    ]
