# Generated by Django 6.0 on 2026-01-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_app", "0002_alter_course_options_alter_lesson_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="course_images/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="preview_image",
            field=models.ImageField(blank=True, null=True, upload_to="lesson_images/"),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
