# Generated by Django 6.0 on 2026-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_app", "0008_alter_lesson_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
