# Generated by Django 5.2.10 on 2026-02-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education_app", "0009_course_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="id",
            field=models.AutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
