# Generated by Django 6.0 on 2026-01-11 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="owner",
            field=models.ForeignKey(
                default=6,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
