# Generated by Django 6.0 on 2026-01-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_payment_checkout_url_payment_stripe_price_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="stripe_status",
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("cash", "Наличные"),
                    ("transfer", "Перевод на счет"),
                    ("stripe", "Stripe"),
                ],
                max_length=10,
            ),
        ),
    ]
