services:
  backend:
    build: .
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
      - celery
      - celery-beat

  db:
    image: postgres:13
    env_file:
      - ../.env
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:6
    env_file:
      - ../.env
    expose:
      - "6379"

  celery:
    build: .
    command: celery -A proj worker --loglevel=info
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A proj beat --loglevel=info
    env_file:
      - ../.env
    environment:
      - CELERY_BROKER_URL=redis://redis:6379
      - CELERY_RESULT_BACKEND=redis://redis:6379
    depends_on:
      - redis
      - db

volumes:
  postgres_data: